[applications.main]
use = "graphorrhea:main"

"pyramid.reload_templates" = true
"pyramid.includes" = [
    # "pyramid_debugtoolbar"
]
"pyramid.debug_authorization" = false
"pyramid.debug_notfound" = false
"pyramid.debug_routematch" = false
"debugtoolbar.intercept_exc" = false
"pyramid.default_locale_name" = "en"
"acidfs.repository_path" = "{here}/database.git"
"sqlalchemy.url" = "sqlite:///test.sqlite3"
"graphorrhea.data" = "{here}/data"
"jwt.private_key" = "what"

"cors.origins" = ["http://127.0.0.1:6543"]
# 24 hours
"cors.max_age" = "86400"
"cors.methods" = ["POST", "PUT", "PATCH", "DELETE", "GET"]
"cors.headers" = ["Content-Type", "Authorization"]

[pshell]
setup = "graphorrhea.pshell:setup"

[servers.main]
use = "waitress:serve"
listen = "0.0.0.0:6543"


[logging]
version = 1

[logging.root]
level = "INFO"
handlers = ["console"]

[logging.logger.graphorrhea]
level = "DEBUG"
handlers = []
qualname = "graphorrhea"

[logging.handlers.console]
class = "logging.StreamHandler"
level = "NOTSET"
formatter = "generic"
stream = "ext://sys.stdout"

[logging.formatters.generic]
format = "%(asctime)s %(levelname)-5.5s [%(name)s:%(lineno)s][%(threadName)s] %(message)s"
