openapi: "3.0.1"
servers:
  - url: /api/v1
info:
  title: Notes API
  version: '1'
paths:
  /users:
    summary: List of users registered on the server.
    get:
      responses:
        200:
          description: List of users
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
    post:
      summary: Create a new user
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - username
                - name
                - password
              properties:
                username:
                  type: string
                name:
                  type: string
                password:
                  type: string
                  format: password
      responses:
        200:
          description: Successfully created user
          content:
            application/json:
              schema:
                type: object
                required:
                  - id
                properties:
                  id:
                    $ref: '#/components/schemas/UserId'
  # /users/{id}:
  #   get:
  #     summary: Get information about a user
  #     responses:
  #       200:
  #         description: User info
  #         content:
  #           application/json:
  #             schema:
  #               $ref: '#/components/schemas/User'
  # /me:
  #   get:
  #     summary: Get the currently active users information
  #     responses:
  #       200:
  #         description: Current user info
  #         content:
  #           application/json:
  #             schema:
  #               $ref: '#/components/schemas/User'
  # /notes:
  #   get:
  #     summary: Show the notes on the server
  #     parameters:
  #       - in: query
  #         name: path
  #         required: true
  #         schema: string
  #     responses:
  #       200:
  #         description: List of notes on the server
  #         content:
  #           application/json:
  #             schema:
  #               type: array
  #               items:
  #                 type: string

components:
  schemas:
    NotePath:
      type: string
      format: regex
      pattern: '(/[a-zA-Z0-9_- ]+)+|/'
    Timestamp:
      type: string
      format: date-time
    UserId:
      type: string
      format: uuid
    Note:
      type: object
      required:
        - owner_id
        - created
        - modified
        - uri
      properties:
        owner_id:
          $ref: '#/components/schemas/UserId'
        created:
          $ref: '#/components/schemas/Timestamp'
          description: When the document was created
        modified:
          $ref: '#/components/schemas/Timestamp'
          description: When the document was last modified
        uri:
          type: string
          description: Location of the document content.
          format: uri-reference
    User:
      type: object
      required:
        - username
        - name
        - id
      properties:
        name:
          type: string
        username:
          type: string
        id:
          $ref: '#/components/schemas/UserId'