"""Initial migration

Revision ID: e06e4fe69c92
Revises: 
Create Date: 2021-03-16 20:07:07.261048

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "e06e4fe69c92"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.Text(), nullable=False),
        sa.Column(
            "password",
            sa.Text(),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("username", name=op.f("uq_users_username")),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("users")
    # ### end Alembic commands ###
